#!/bin/sh

# I had issues with --output default, so I choose to get the 1st connected output xrandr gets
output=$(xrandr -q | grep " connected" | awk '{ print $1 }')

# This is used to change the backlight
device=$(ls /sys/class/backlight/)

# Used to change gamma and/or brightness via xrandr
gamma="1:1:1"
brightness="1"

print_help() {
	echo "usage : ${0} [OPTION]..."
	echo ""
	echo "Options :"
	echo "  -g, --gamma R:G:B       Changes the gamma through xrandr"
	echo "      --brightness NUM    Changes the brightness through xrandr"
	echo "                          only use it with NUM > 1, -b should be used otherwise"
	echo "  -r, --reset             Resets xrandr values"
	echo "  -b, --backlight NUM     Changes the backlight (NUM should be between 1 and 256)"
	echo "  -t, --temperature NUM   Not yet implemented"
	echo "  -h, --help              Display help"
}

backlight() {
	echo ${1} | sudo tee -a /sys/class/backlight/$device/brightness > /dev/null
}

reset_xrandr() {
	xrandr --output $output --gamma 1:1:1 --brightness 1
}

if [ ${#} = 0 ]; then
	print_help
	exit 0
fi

# Parsing arguments (god, I love this way of doing it)
while [ ${#} != 0 ]; do
	case "${1}" in
	-h | --help)
		print_help
		exit 0;;
	-g | --gamma)
		gamma=${2}
		xrandr_changed=true
		shift 2;;
	--brightness)
		brightness=${2}
		xrandr_changed=true
		shift 2;;
	-b | --backlight)
		backlight ${2}
		shift 2;;
	-r | --reset)
		reset_xrandr
		shift;;
	*)
		print_help
		exit 0;;
	esac
done

# I have to do both at once, xrandr doesn't like doing one then the other.
if [ "$xrandr_changed" = "true" ]; then
	# That ridiculous case is donc to be able to enter only 1 value into gamma.
	case "$gamma" in
		*:*)
			;;
		*)
			gamma="$gamma:$gamma:$gamma"
			;;
	esac
	xrandr --output $output --gamma $gamma --brightness $brightness
fi

#if [ $# -eq 1 ]; then
#	if [ $1 -le 6600 ]; then
#		RED=$(awk "BEGIN {print 1}")
#		GREEN=$(awk "BEGIN {print (99.4708025861 * log($1/100) - 161.1195681661)}")
#		BLUE=$(awk "BEGIN {print (138.5177312231 * log($1/100 - 10) - 305.0447927307)}")
#	else
#		RED=$(awk "BEGIN {print (329.698727446 * ($1/100 - 60) ^ (-0.1332047592))}")
#		GREEN=$(awk "BEGIN {print (288.1221695283 * ($1/100 - 60) ^ (-0.0755148492))}")
#		BLUE=255
#	fi
#	echo "$RED $GREEN $BLUE"
#	# xrandr --output $output --gamma $RED:$GREEN:$BLUE
#fi